### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by piotrpodlewski**
thank you for the contest, it was a big pleasure!

### CODE REVIEW

**Comment by ekstroem** [comment]
Thanks

**Comment by piotrpodlewski** [comment]
hello, are my predictions valid? I don't see my result (0.1054285) listed. thanks!

**Comment by ekstroem** [comment]
Ah Damn. Yes they are good. They were just not in the contributions directory so I overlooked them. Will rerun the analyses and update the blog post right away. Sorry

**Comment by ekstroem** [comment]
Sorry! Fixed in the blog post

**Comment by piotrpodlewski** [comment]
no problem at all, thank you so much! glad to hear they are valid :)

**Pull request merged**
